---
- hosts: localhost
  name: Create DO Server
  tasks:
    - name: Create DO Server
      community.digitalocean.digital_ocean_droplet:
        image_id: "ubuntu-22-04-x64"
        name: "minecraft-server"
        region_id: "FRA1"
        size_id: "s-1vcpu-1gb"
        unique_name: true
        user_data: "lookup('ansible.builtin.file','../inventory/cloud-init.yml')"
        ssh_keys:
          - 59:10:d9:a4:5d:04:d7:00:c2:7e:fb:bd:1c:18:75:ee
          - d1:9a:f7:9d:72:7e:e5:ec:47:31:00:6f:3c:40:b7:28
      register: server_info

    - name: out test server_info
      ansible.builtin.debug:
        var: server_info 
        
    - name: Get IP and ID
      ansible.builtin.set_fact:
        droplet_ip: "{{ server_info.data.droplet.networks.v4[0].ip_address }}"
        droplet_id: "{{ server_info.data.droplet.id }}"
