---
- hosts: localhost
  name: Create DO Server
  tasks:
    - name: Get GitHub Contributors
      ansible.builtin.uri:
        url: "https://api.github.com/repos/ntatrishvili/minecraft_server/contributors"
        headers:
          Content-Type: application/json
      register: results

    - name: Set Facts
      ansible.builtin.set_fact:
        gh_users: |-
          {{
            results['json']
            |map(attribute="login")
          }}

    - name: Create DO Server
      community.digitalocean.digital_ocean:
        image_id: "ubuntu-22-04-x64"
        name: "minecraft-server"
        region_id: "FRA1"
        size_id: "s-2vcpu-2gb"
        unique_name: true
        user_data: |-
          {{
            lookup('ansible.builtin.template','../inventory/files/cloud-init.yml')
          }}
        
