- hosts: minecraft
  name: install docker
  become: true
  tasks: 
    - name: test
      ansible.builtin.debug:
        var: ansible_user
    - name: invoke docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true