---
- hosts: minecraft-server
  name: Common
  pre_tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - name: test
      ansible.builtin.debug:
        var: ansible_user

    - name: invoke docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
