---
- hosts: all
  name: Common
  become: true
  pre_tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - name: invoke docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: true
