#cloud-config

groups:
  - mc

users:
  - name: minecraft
    shell: /usr/sbin/nologin
    groups: mc
  - name: nia
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:ntatrishvili
  - name: luka
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:dr-mato
  - name: samer
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:samerbahri98

package_update: true
package_upgrade: true
