#cloud-config

groups:
  - docker

users:
{% for user in gh_users %}
  - name: "{{ user }}"
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    ssh_import_id:
      - "gh:{{ user }}"
{% endfor %}

package_update: true
package_upgrade: true
