---
name: Backup Server

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Get Server IP
        run: doctl compute droplet get ${{ vars.DO_INSTANCE }} --no-header --template {{.PublicIPv4}}
        id: do_instance_ip

